import { BadRequestException, Injectable, InternalServerErrorException } from '@nestjs/common';
import { Octokit } from '@octokit/rest';
import { PullRequestDto } from './git-bridge.dto';
import * as fs from 'fs';
import * as path from 'path';

@Injectable()
export class GitBridgeService {
  private findRootDir(): string {
    const candidates = [
      path.resolve(process.cwd(), '..'),
      process.cwd(),
      path.resolve(__dirname, '../../../..'),
      path.resolve(__dirname, '../../..'),
    ];
    for (const cand of candidates) {
      if (fs.existsSync(path.join(cand, 'caliper.yml')) || fs.existsSync(path.join(cand, 'datasets'))) {
        return cand;
      }
    }
    return candidates[0];
  }

  async listFiles(): Promise<string[]> {
    const rootDir = this.findRootDir();
    const fileSet = new Set<string>(['caliper.yml', 'datasets/geography-qa.yml', 'datasets/code-generation.yml']);
    const datasetsDir = path.join(rootDir, 'datasets');
    if (fs.existsSync(datasetsDir)) {
      try {
        const items = fs.readdirSync(datasetsDir);
        for (const item of items) {
          if (item.endsWith('.yml') || item.endsWith('.yaml')) {
            fileSet.add(`datasets/${item}`);
          }
        }
      } catch (e) {}
    }
    return Array.from(fileSet);
  }

  async getFileContent(filePath: string): Promise<string> {
    const rootDir = this.findRootDir();
    const safePath = path.normalize(filePath).replace(/^(\.\.[\/\\])+/, '');
    const absolutePath = path.join(rootDir, safePath);
    if (fs.existsSync(absolutePath)) {
      return fs.readFileSync(absolutePath, 'utf8');
    }

    // Fallback embedded contents if file system path not mounted in container
    if (filePath === 'datasets/geography-qa.yml') {
      return `datasets:
  - id: geography-qa
    name: "Geography Q&A"
    profile: mock-geography
    test_cases:
      - id: tc-france-capital
        prompt: "What is the capital of France?"
        expected: "Paris"
      - id: tc-japan-capital
        prompt: "What is the capital of Japan?"
        expected: "Tokyo"
    evaluators:
      - id: regex-capitals
        type: regex
        params:
          pattern: "(?i)paris|tokyo"`;
    }

    if (filePath === 'datasets/code-generation.yml') {
      return `datasets:
  - id: code-generation
    name: "Code Generation"
    profile: mock-code
    test_cases:
      - id: tc-fizzbuzz
        prompt: "Write a Python function that returns FizzBuzz for numbers 1-20."
    evaluators:
      - id: contains-def
        type: regex
        params:
          pattern: "def\\\\s+\\\\w+"`;
    }

    throw new BadRequestException(`File not found: ${filePath}`);
  }

  async createPullRequest(input: PullRequestDto, userToken?: string): Promise<{ number: number; url: string; branch: string }> {
    const token = userToken || process.env.GITHUB_TOKEN;
    if (!token) throw new InternalServerErrorException('No GitHub token available. Set GITHUB_TOKEN or supply token in user settings.');
    const [owner, repo] = input.repository.split('/');
    const octokit = new Octokit({ auth: token });
    try {
      const base = await octokit.rest.repos.getBranch({ owner, repo, branch: 'main' });
      const branch = `caliper/${input.branch_name}`;
      try {
        await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: base.data.commit.sha });
      } catch (error: unknown) {
        if ((error as { status?: number }).status !== 422) throw error;
      }
      let sha: string | undefined;
      try {
        const content = (await octokit.rest.repos.getContent({ owner, repo, path: input.file_path, ref: branch })).data;
        if (!Array.isArray(content) && 'sha' in content) sha = content.sha;
      } catch (error: unknown) { if ((error as { status?: number }).status !== 404) throw error; }
      await octokit.rest.repos.createOrUpdateFileContents({ owner, repo, path: input.file_path, message: `chore(caliper): update ${input.file_path}`, content: Buffer.from(input.yaml, 'utf8').toString('base64'), branch, sha });
      const pr = await octokit.rest.pulls.create({ owner, repo, title: input.title, head: branch, base: 'main', body: 'Generated by the Caliper dashboard.' });
      return { number: pr.data.number, url: pr.data.html_url, branch };
    } catch (error: unknown) {
      if (error instanceof BadRequestException || error instanceof InternalServerErrorException) throw error;
      throw new BadRequestException(`GitHub bridge failed: ${(error as Error).message}`);
    }
  }
}
